authClassname: horses\plugin\doctrine\DbAuth
userClassname: vino\User
noAuthRedirect: auth/login
mode: defaultProtected
invertAuth:
  - auth/login
  - auth/register
  - arrival/index
  - defaulter/watchman
